update:
	npm update elm-accordion
	# elm install hallelujahdrive/elm-accordion
	curl https://raw.githubusercontent.com/hallelujahdrive/elm-accordion/master/demo/src/Main.elm > src/Main.elm
	curl https://raw.githubusercontent.com/hallelujahdrive/elm-accordion/master/demo/src/Main.elm.d.ts > src/Main.elm.d.ts
	curl -O https://raw.githubusercontent.com/hallelujahdrive/elm-accordion/master/demo/demo.scss

build:
	rollup -c

clean:
	rm demo.js demo.css